### ISSUE TITLE
Chose Package / Software Name

### ISSUE THREAD

**Issue by douglowe** [LightForm-group/KWN-deformation#14]
A name is needed for the executable (rather than a.out).

**Comment by mbignon** [comment]
KWN.out ?

**Comment by douglowe** [comment]
We could use KWN (either with .out, .exe, or similar). Do you know if there any other KWN models already publically available? And would it be useful to highlight either processes (e.g. KWNdeform), or the group (KWNLightForm)?

**Comment by samuel-hg-engel** [comment]
There is kawin (https://kawin.org/), which is a python implementation, but it doesn't include deformation.

**Comment by douglowe** [comment]
I wonder how they came up with that expansion of KWN.

Possibilities:
f-KWN | KWN-f (to note that it is fortran based)
KWN-deform (if the principle additional feature of the model will remain deformation?)
KWN-lf (to link this to the LightForm group)

Do any of these appeal?

**Comment by mbignon** [comment]
I would go for KWN-deform I think, this is what is different from what already exists

**Comment by douglowe** [comment]
KWN-deform works for me - as long as you're all happy that this name won't become anachronistic as the model is extended?
