### ISSUE TITLE
Testing - with small example results

### ISSUE THREAD

**Issue by douglowe** [LightForm-group/KWN-deformation#20]
We need some small example outputs for testing to ensure code still generates expected results.

Needs to be examples runnable within ~5 minutes (or so)

Look at diff'ing the text files.

**Comment by mbignon** [comment]
I've changed the way to run the code, now it takes as an input the name of the folder where the input file is located. 
for example:
./run_kwn.sh test_1
There are now two tests which I've put in test_1 and test_2 folders. These tests are described in a textfile. 

Remark: we might make changes that allow more precise results or correct some small problems that will slightly affect the results. To be able to make a rough check and see if further development still give the same results as before, I've included a jupyter notebook in each test that produces figures. These figures can be compared with the ones in "reference_results_and_figures" folder.
