### ISSUE TITLE
Alternative Fortran Input Methods

### ISSUE THREAD

**Issue by douglowe** [LightForm-group/KWN-deformation#24]
For future development it would be good to move to a structured input file format. This could be the fortran namelist format, or something like [TOML](https://toml-f.readthedocs.io/en/latest/). Both of these would allow for labeled data to be input, making the input method less error-prone.

The TOML system is used by fpm for it's configuration files. And it can be loaded simply as a dependency by including the following code into the `fpm.toml` build file:
```
[dependencies]
toml-f.git = "https://github.com/toml-f/toml-f"
```

**Comment by mbignon** [comment]
Would be good I think
